import json

import pytest

from src.agent.agent_builder import agent_executor_builder
from src.agent.prompt_templates import system_prompt
from src.utils import extract_selected_threads_processed, get_exact_answers


@pytest.fixture
def sample_input(tmp_path):
    data = {
        "pre_text": [
            "26 | 2009 annual report in fiscal 2008 , revenues in the credit union systems and services business segment increased 14% ( 14 % ) from fiscal 2007 .",
            "all revenue components within the segment experienced growth during fiscal 2008 .",
            "license revenue generated the largest dollar growth in revenue as episys ae , our flagship core processing system aimed at larger credit unions , experienced strong sales throughout the year .",
            "support and service revenue , which is the largest component of total revenues for the credit union segment , experienced 34 percent growth in eft support and 10 percent growth in in-house support .",
            "gross profit in this business segment increased $ 9344 in fiscal 2008 compared to fiscal 2007 , due primarily to the increase in license revenue , which carries the highest margins .",
            "liquidity and capital resources we have historically generated positive cash flow from operations and have generally used funds generated from operations and short-term borrowings on our revolving credit facility to meet capital requirements .",
            "we expect this trend to continue in the future .",
            "the company 2019s cash and cash equivalents increased to $ 118251 at june 30 , 2009 from $ 65565 at june 30 , 2008 .",
            "the following table summarizes net cash from operating activities in the statement of cash flows : 2009 2008 2007 .",
        ],
        "post_text": [
            "year ended june 30 , cash provided by operations increased $ 25587 to $ 206588 for the fiscal year ended june 30 , 2009 as compared to $ 181001 for the fiscal year ended june 30 , 2008 .",
            "this increase is primarily attributable to a decrease in receivables compared to the same period a year ago of $ 21214 .",
            "this decrease is largely the result of fiscal 2010 annual software maintenance billings being provided to customers earlier than in the prior year , which allowed more cash to be collected before the end of the fiscal year than in previous years .",
            "further , we collected more cash overall related to revenues that will be recognized in subsequent periods in the current year than in fiscal 2008 .",
            "cash used in investing activities for the fiscal year ended june 2009 was $ 59227 and includes $ 3027 in contingent consideration paid on prior years 2019 acquisitions .",
            "cash used in investing activities for the fiscal year ended june 2008 was $ 102148 and includes payments for acquisitions of $ 48109 , plus $ 1215 in contingent consideration paid on prior years 2019 acquisitions .",
            "capital expenditures for fiscal 2009 were $ 31562 compared to $ 31105 for fiscal 2008 .",
            "cash used for software development in fiscal 2009 was $ 24684 compared to $ 23736 during the prior year .",
            "net cash used in financing activities for the current fiscal year was $ 94675 and includes the repurchase of 3106 shares of our common stock for $ 58405 , the payment of dividends of $ 26903 and $ 13489 net repayment on our revolving credit facilities .",
            "cash used in financing activities was partially offset by proceeds of $ 3773 from the exercise of stock options and the sale of common stock ( through the employee stock purchase plan ) and $ 348 excess tax benefits from stock option exercises .",
            "during fiscal 2008 , net cash used in financing activities for the fiscal year was $ 101905 and includes the repurchase of 4200 shares of our common stock for $ 100996 , the payment of dividends of $ 24683 and $ 429 net repayment on our revolving credit facilities .",
            "cash used in financing activities was partially offset by proceeds of $ 20394 from the exercise of stock options and the sale of common stock and $ 3809 excess tax benefits from stock option exercises .",
            "beginning during fiscal 2008 , us financial markets and many of the largest us financial institutions have been shaken by negative developments in the home mortgage industry and the mortgage markets , and particularly the markets for subprime mortgage-backed securities .",
            "since that time , these and other such developments have resulted in a broad , global economic downturn .",
            "while we , as is the case with most companies , have experienced the effects of this downturn , we have not experienced any significant issues with our current collection efforts , and we believe that any future impact to our liquidity will be minimized by cash generated by recurring sources of revenue and due to our access to available lines of credit. .",
        ],
        "filename": "JKHY/2009/page_28.pdf",
        "table_ori": [
            ["", "Year ended June 30, 2009"],
            ["2008", "2007"],
            ["Net income", "$103,102", "$104,222", "$104,681"],
            ["Non-cash expenses", "74,397", "70,420", "56,348"],
            ["Change in receivables", "21,214", "(2,913)", "(28,853)"],
            ["Change in deferred revenue", "21,943", "5,100", "24,576"],
            ["Change in other assets and liabilities", "(14,068)", "4,172", "17,495"],
            ["Net cash from operating activities", "$206,588", "$181,001", "$174,247"],
        ],
        "table": [
            [
                "2008",
                "year ended june 30 2009 2008",
                "year ended june 30 2009 2008",
                "year ended june 30 2009",
            ],
            ["net income", "$ 103102", "$ 104222", "$ 104681"],
            ["non-cash expenses", "74397", "70420", "56348"],
            ["change in receivables", "21214", "-2913 ( 2913 )", "-28853 ( 28853 )"],
            ["change in deferred revenue", "21943", "5100", "24576"],
            [
                "change in other assets and liabilities",
                "-14068 ( 14068 )",
                "4172",
                "17495",
            ],
            ["net cash from operating activities", "$ 206588", "$ 181001", "$ 174247"],
        ],
        "qa": {
            "question": "what was the percentage change in the net cash from operating activities from 2008 to 2009",
            "exe_ans": 0.14136,
        },
    }
    sample_file = tmp_path / "sample.json"
    sample_file.write_text(json.dumps([data]))
    return str(sample_file)


def test_agent_integration(sample_input):
    memory_flag = False

    # Load the test data
    with open(sample_input, "r") as f:
        data = json.load(f)

    # Process the data using your utility functions
    data_processed = extract_selected_threads_processed(data)
    print(f"Processed data: {data_processed}")
    # Assume we select the first thread for getting exact answers.
    exact_answers, single_sample = get_exact_answers(data_processed[0])
    print(f"Exact answers: {exact_answers}")
    print(f"Single sample: {single_sample}")

    # For testing, we'll use the sample extracted input (single_sample) as our model input.
    model_input = single_sample

    # Build the agent executor using test parameters.
    tools = []  # Provide dummy or mocked tools as needed.
    agent_executor, memory = agent_executor_builder(
        provider="openai",
        model="gpt-4o",
        temperature=0,
        tools=tools,
        prompt_style="json-chat",
        memory_flag=memory_flag,
    )

    # For non-interactive testing, simulate the invocation with a test input.
    test_input = (
        f"{system_prompt}. Pay attention to the format it must respect the guidelines. "
        f"Task: Given the following input extract the informations and then answer "
        f"the corresponding questions in the input. Do not output any explanantion in the output only the answer {model_input}"
    )
    response = agent_executor.invoke({"input": test_input})

    # Assertions: Check that the output structure is as expected.
    # Here we assume the output is a comma-separated string.
    answers = response["output"].split(",")
    print(f"answers: {answers}")
    # print answer data type
    print(f"answers data type: {type(answers)}")
    assert len(answers) > 0, "Expected at least one answer in the output."
    assert all(
        answer.strip() for answer in answers
    ), "All answers should be non-empty strings."

    # Check if the calculated answer approximates the expected answer from the qa field in the original JSON.
    # Note: data["qa"]["exe_ans"] is a numeric value (0.14136) and answers[0] is expected to be a percentage number.
    try:
        # Convert the answer to float. Adjust conversion if your agent returns e.g. "14.1%" (strip the %).
        first_answer = answers[0].strip().rstrip("%")
        first_answer = (
            float(first_answer) / 100
            if float(first_answer) > 1
            else float(first_answer)
        )
    except ValueError:
        pytest.fail("The first answer is not a valid number.")


if __name__ == "__main__":
    pytest.main([__file__])
